from __future__ import annotations

from hashlib import sha256
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INSTRUCTIONS_PATH = ROOT / ".github" / "copilot-instructions.md"
AGENT_PATH = ROOT / ".github" / "agents" / "arquivo-arcano.agent.md"


def render_agent(instructions: str) -> str:
    digest = sha256(instructions.encode("utf-8")).hexdigest()
    return f"""---
name: "Arquivo Arcano"
description: "Use when implementing, debugging, reviewing, or testing the Arquivo Arcano local-first RPG rules search application."
tools: [read, search, edit, execute]
user-invocable: true
---
<!-- Generated by scripts/update_agent.py from .github/copilot-instructions.md. -->
<!-- source-sha256: {digest} -->

Follow the project instructions below. Treat them as the source of truth for architecture,
privacy, implementation, interface, and validation decisions. Do not edit this generated file
directly; update `.github/copilot-instructions.md` instead.

{instructions.strip()}
"""


def main() -> None:
    instructions = INSTRUCTIONS_PATH.read_text(encoding="utf-8")
    content = render_agent(instructions)
    if AGENT_PATH.exists() and AGENT_PATH.read_text(encoding="utf-8") == content:
        return
    AGENT_PATH.parent.mkdir(parents=True, exist_ok=True)
    AGENT_PATH.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()